### ISSUE TITLE
Dockerfile for jamrizzi/elk

### ISSUE THREAD

**Issue by yayitswei** [jamrizzi/elk-filebeat#1]
Thanks for making this example!

In the compose file you reference jamrizzi/elk, which I see on DockerHub but not on Github. Would you mind publishing that as well so I can see how it fits together? I would like to see how it differs from [this image](https://github.com/spujadas/elk-docker).

**Comment by clayrisser** [comment]
https://github.com/jamrizzi/elk-filebeat/blob/master/filebeat/Dockerfile

**Comment by clayrisser** [comment]
https://github.com/jamrizzi/elk-filebeat/blob/master/elk/Dockerfile

**Comment by clayrisser** [comment]
I'm sourcing the `sebp/elk` container and adding my own config that works with filebeat.

**Comment by yayitswei** [comment]
Ah I see, makes sense now. Thanks for your help!
